### ISSUE TITLE
Getting expenses-list.html:85 Uncaught TypeError: Cannot set property 'renderer' of undefinedonImportLoaded @ (index):38 while running the app

### ISSUE THREAD

**Issue by mamidishetti** [vaadin-marcus/polymer-spring-boot#1]
Getting expenses-list.html:85 Uncaught TypeError: Cannot set property 'renderer' of undefinedonImportLoaded @ (index):38 while running the app

**Comment by apklein** [comment]
@mamidishetti @vaadin-marcus did you resolved?

**Comment by marcushellberg** [comment]
Sorry, didn't see this ticket until now. It was filed while I was on vacation. The API for adding renderers for the vaadin-grid cells had changed a bit, should work now.
