### ISSUE TITLE
Page visibility restrictions

### ISSUE THREAD

**Issue by HJK181** [vaadin-marcus/polymer-spring-boot#4]
Hi,

first of all thank you for the great example. I tried out the project and thought what may happen if someone just changes the token via developer console. e.g.: $0.token=123

What happens is, that you by pass the login-page and the expenses-page is showing up. There is no data of course by I think it's ugly to present internal views to users trying to hack around.

Do you know any way to prevent a user from accessing views by manipulating variables? Is this possible at all on client side rendered pages?

Thanks in advance.

**Comment by marcushellberg** [comment]
You could for instance have the protected assets in another folder with access restrictions and load them dynamically using `Polymer.importHref()` only after authentication. But in the end, there's no way of preventing users from modifying the running page on the client, so you should not have any business sensitive logic or data in them.

**Comment by HJK181** [comment]
Thank you very much.
