### ISSUE TITLE
polymer3-spring-boot

### ISSUE THREAD

**Issue by ArvindAkula** [vaadin-marcus/polymer-spring-boot#5]
Thank you Marcus for this excellent example with SpringBoot+Polymer. However do you have any sample with Polymer3+Springboot . I tried to follow the migration guide to convert this project and facing some issues.https://polymer-library.polymer-project.org/3.0/docs/upgrade

**Comment by marcushellberg** [comment]
Sorry, I don't have a project with P3 and Spring Boot. The company I work for is working on a pretty cool tool that allows you to build apps that use Spring Boot on the backend and LitElement (basically the next generation of Polymer) that you can check out here https://vaadin.com/labs/vaadin-connect. It's still in preview though.
